export { default as Youtube } from './Youtube'
export { default as Bg1 } from './Bg1'
export { default as Arrow } from './Arrow'
export { default as Coding } from './Coding'
export { default as TechnicalSupport } from './TechnicalSupport'