export { default as NobleLeadersIcon } from './imgs/noble-l.jpg';
export { default as BhutanotelIcon } from './imgs/bhutanotel.png';
export { default as HeroprojectIcon } from './imgs/heroproject.png';
export { default as PhotographyIcon } from './imgs/photography.png';
export { default as pwdMakerIcon } from './imgs/pwd_maker.png';
export { default as CarServicesIcon } from './imgs/sim_vices.png';
export { default as ProtoFolioIcon } from './imgs/proto-folio.png';
export { default as HeroBackground } from './imgs/hero_bg.png';
export { default as FooterBackground } from './imgs/footer_bg.png';